# Loading

This notebooks shows how to load graphs from existing datasets, [NetSets](https://graphs.telecom-paristech.fr/) and [Konect](http://konect.uni-koblenz.de).

In [1]:
from sknetwork.data import load_netset, load_konect

## Graph

In [2]:
graph = load_konect('dolphins')

In [3]:
graph.adjacency

<62x62 sparse matrix of type '<class 'numpy.int64'>'
	with 318 stored elements in Compressed Sparse Row format>

In [4]:
graph = load_netset('openflights')

In [5]:
graph.adjacency

<3097x3097 sparse matrix of type '<class 'numpy.int64'>'
	with 36386 stored elements in Compressed Sparse Row format>

In [6]:
graph.names

array(['Goroka Airport', 'Madang Airport', 'Mount Hagen Kagamuga Airport',
       ..., 'Saumlaki/Olilit Airport', 'Tarko-Sale Airport',
       'Alashankou Bole (Bortala) airport'], dtype='<U65')

In [7]:
graph.position

array([[145.39199829,  -6.08168983],
       [145.78900147,  -5.20707989],
       [144.29600525,  -5.82678986],
       ...,
       [131.30599976,  -7.98860979],
       [ 77.81809998,  64.93080139],
       [ 82.3       ,  44.895     ]])

## Digraph

In [8]:
graph = load_netset('wikivitals')

In [9]:
graph.adjacency

<10012x10012 sparse matrix of type '<class 'numpy.int64'>'
	with 792091 stored elements in Compressed Sparse Row format>

In [10]:
graph.names

array(['The arts', 'Art', 'Architecture', ..., 'Baby transport',
       'Pipeline transport', 'Tractor'], dtype='<U62')

In [11]:
graph.labels

array([ 0,  0,  0, ..., 10, 10, 10])

In [12]:
graph.names_labels

array(['Arts', 'Biology and health sciences', 'Everyday life',
       'Geography', 'History', 'Mathematics', 'People',
       'Philosophy and religion', 'Physical sciences',
       'Society and social sciences', 'Technology'], dtype='<U27')

In [13]:
graph.labels_hierarchy

array([  18,   18,    2, ..., 1729, 1729, 1729])

In [14]:
graph.names_labels_hierarchy

array(['Arts', 'Arts.Architecture', 'Arts.Architecture.General', ...,
       'Technology.Transportation.Road transport.Driving',
       'Technology.Transportation.Road transport.Road',
       'Technology.Transportation.Road transport.Road.Highway'],
      dtype='<U136')

## Bigraphs

In [15]:
graph.biadjacency

<10012x31323 sparse matrix of type '<class 'numpy.int64'>'
	with 995919 stored elements in Compressed Sparse Row format>

In [16]:
graph.names

array(['The arts', 'Art', 'Architecture', ..., 'Baby transport',
       'Pipeline transport', 'Tractor'], dtype='<U62')

In [17]:
graph.names_col

array(['moos', 'tonnag', 'separatist', ..., 'luteum', 'radiat', 'helena'],
      dtype='<U22')